language: elixir
elixir:
  - 1.5.3
  - 1.6.6
  - 1.7.3
sudo: required
env:
  matrix:
  - ES_VERSION=2.4.6
  - ES_VERSION=5.6.12
  - ES_VERSION=6.0.1
  - ES_VERSION=6.1.1
  - ES_VERSION=6.2.4
  - ES_VERSION=6.3.2
  - ES_VERSION=6.4.1

before_install:
  - sudo dpkg -r elasticsearch
  - case "$ES_VERSION" in
    "") ;;

    "2.4.6")
      export ES_VERSION=2.4.6 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "5.6.12")
      export ES_VERSION=5.6.12 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.0.1")
      export ES_VERSION=6.0.1 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.1.1")
      export ES_VERSION=6.1.1 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.2.4")
      export ES_VERSION=6.2.4 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.3.2")
      export ES_VERSION=6.3.2 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.4.1")
      export ES_VERSION=6.4.1 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;
   esac
before_script:
  - sleep 10
  # Outputs info about ES, including version number. Useful for debugging.
  - curl localhost:9200
script:
  - mix test --include integration
  - mix credo --strict

